---
# Synopsis: Ignore test objects by name.
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressWithTargetName
spec:
  rule:
  - 'Azure.Resource.UseTags'
  if:
    anyOf:
    - name: '.'
      equals: 'NetworkWatcherRG'
    - name: '.'
      equals: 'jake-test-vnet-01'
