---
# Synopsis: Ignore test objects by name.
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressWithTargetName
spec:
  rule:
  - 'Azure.Resource.UseTags'
  if:
    name: '.'
    equals: 'NetworkWatcherRG'
